version: "3.7"

services:
  test-postgres-db-docs-snippets:
    image: postgres:11
    container_name: test-postgres-db-docs-snippets
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    networks:
      - postgres
