[build-system]
requires = [
    "setuptools>=69.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "dagster-airlift"
version = "0.28.15rc4"
description = "A toolkit for observing integration and migration between Apache Airflow and Dagster."
authors = [
    { name = "Dagster Labs", email = "hello@dagsterlabs.com" },
]
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-airlift"

[project.scripts]
dagster-airlift = "dagster_airlift.cli:cli"

[project.entry-points."dagster_dg_cli.registry_modules"]
"dagster_airlift.core.components" = "dagster_airlift.core.components"

[project.optional-dependencies]
core = [
    "dagster==1.12.15rc4",
    "click",
    "structlog",
]
in-airflow = [
    "click",
    "structlog",
]
tutorial = [
    "dagster-webserver==1.12.15rc4",
    "apache-airflow==2.9.3; python_version < '3.12'",
    "marshmallow==3.20.1; python_version < '3.12'",
    "pendulum>=2.0.0,<4.0.0; python_version < '3.12'",
    "apache-airflow>=2.9.0; python_version >= '3.12'",
    "marshmallow==3.23.1; python_version >= '3.12'",
    "pendulum>=3.0.0; python_version >= '3.12'",
    "flask-session<0.6.0",
    "connexion<3.0.0",
    "fastapi<0.118",
    "click",
    "structlog",
]
mwaa = [
    "boto3>=1.18.0",
]
test = [
    "pytest",
    "dagster-dbt==0.28.15rc4",
    "dbt-duckdb",
    "boto3",
    "dagster-webserver==1.12.15rc4",
    "apache-airflow==2.9.3; python_version < '3.12'",
    "marshmallow==3.20.1; python_version < '3.12'",
    "pendulum>=2.0.0,<4.0.0; python_version < '3.12'",
    "apache-airflow>=2.9.0; python_version >= '3.12'",
    "marshmallow==3.23.1; python_version >= '3.12'",
    "pendulum>=3.0.0; python_version >= '3.12'",
    "flask-session<0.6.0",
    "connexion<3.0.0",
    "fastapi<0.118",
    "click",
    "structlog",
]

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "dagster_airlift_tests*",
    "kitchen-sink",
    "perf-harness",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "tox.ini",
    "pytest.ini",
    "dagster_airlift_tests/**",
]
