[build-system]
requires = ["setuptools>=69.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dagster-airlift"
version = "1!0+dev"
description = "A toolkit for observing integration and migration between Apache Airflow and Dagster."
authors = [{name = "Dagster Labs", email = "hello@dagsterlabs.com"}]
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-airlift"

[project.scripts]
dagster-airlift = "dagster_airlift.cli:cli"

[project.entry-points."dagster_dg_cli.registry_modules"]
"dagster_airlift.core.components" = "dagster_airlift.core.components"

[project.optional-dependencies]
core = [
    "dagster==1!0+dev",
    "click",
    "structlog",
]
# [in-airflow] doesn't directly have a dependency on airflow because Airflow
# cannot be installed via setup.py reliably. Instead, users need to install from
# a constraints file as recommended by the Airflow project.
in-airflow = [
    "click",
    "structlog",
]
# [tutorial] includes additional dependencies needed to run the tutorial.
# Namely, the dagster-webserver and the constrained airflow packages.
tutorial = [
    "dagster-webserver",
    # Requirements for python versions under 3.12.
    "apache-airflow==2.9.3; python_version < '3.12'",
    "marshmallow==3.20.1; python_version < '3.12'",
    "pendulum>=2.0.0,<4.0.0; python_version < '3.12'",
    # Requirements for python versions 3.12 and above.
    "apache-airflow>=2.9.0; python_version >= '3.12'",
    "marshmallow==3.23.1; python_version >= '3.12'",
    "pendulum>=3.0.0; python_version >= '3.12'",
    # Flask-session 0.6 is incompatible with certain airflow-provided test utilities.
    "flask-session<0.6.0",
    "connexion<3.0.0",  # https://github.com/apache/airflow/issues/35234
    "fastapi<0.118",  # https://github.com/apache/airflow/discussions/57769#discussioncomment-14861217
    "click",
    "structlog",
]
mwaa = [
    "boto3>=1.18.0",  # confirms mwaa is available in the environment
]
test = [
    "pytest",
    "dagster-dbt==1!0+dev",
    "dbt-duckdb",
    "boto3",
    "dagster-webserver==1!0+dev",
    "apache-airflow==2.9.3; python_version < '3.12'",
    "marshmallow==3.20.1; python_version < '3.12'",
    "pendulum>=2.0.0,<4.0.0; python_version < '3.12'",
    "apache-airflow>=2.9.0; python_version >= '3.12'",
    "marshmallow==3.23.1; python_version >= '3.12'",
    "pendulum>=3.0.0; python_version >= '3.12'",
    "flask-session<0.6.0",
    "connexion<3.0.0",
    "fastapi<0.118",
    "click",
    "structlog",
]

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "dagster_airlift_tests*",
    "kitchen-sink",
    "perf-harness",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "tox.ini",
    "pytest.ini",
    "dagster_airlift_tests/**",
]
