3.6.15:
  docker_args:
    BASE_IMAGE: python:3.6.15-slim
    PYTHON_VERSION: 3.6.15
3.7.12:
  docker_args:
    BASE_IMAGE: python:3.7.12-slim
    PYTHON_VERSION: 3.7.12
3.8.12:
  docker_args:
    BASE_IMAGE: python:3.8.12-slim
    PYTHON_VERSION: 3.8.12
3.9.10:
  docker_args:
    BASE_IMAGE: python:3.9.10-slim
    PYTHON_VERSION: 3.9.1
3.10.4:
  docker_args:
    BASE_IMAGE: python:3.10.4-slim
    PYTHON_VERSION: 3.10.4
