3.6.11:
  docker_args:
    BASE_IMAGE: python:3.6.11-slim
    PYTHON_VERSION: 3.6.11
3.7.8:
  docker_args:
    BASE_IMAGE: python:3.7.8-slim
    PYTHON_VERSION: 3.7.8
3.8.3:
  docker_args:
    BASE_IMAGE: python:3.8.3-slim
    PYTHON_VERSION: 3.8.3
