version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "hellendag"
    open-pull-requests-limit: 0
    exclude-paths:
      - "examples/**"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    exclude-paths:
      - "pyright/**"
      - "examples/**"
    open-pull-requests-limit: 0
