[project]
name = "dagster-hightouch"
description = "Dagster library for Hightouch"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dagster>=0.14",
    "requests>=2.0",
]
dynamic = ["version"]

[tool.uv]
dev-dependencies = [
    "pyright>=1.1.386",
    "pytest",
    "ruff>=0.7.2",
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["dagster_hightouch"]

[tool.setuptools.dynamic]
version = {attr = "dagster_hightouch.__version__"}
