default_stages: [pre-commit] # don't run on push by default
repos:
- repo: local
  hooks:
  - id: ruff-format
    name: Ruff Format
    entry: ruff
    args: [format]
    language: system
    pass_filenames: false
  - id: ruff-lint
    name: Ruff Lint
    entry: ruff
    args: [check, --fix, --exit-non-zero-on-fix]
    language: system
    pass_filenames: false
  - id: docs-mdx-format
    name: Format Docs
    language: system
    entry: bash -c "cd docs && make mdx-format"
    pass_filenames: false
    files: ^docs/content

  # We do not use pyright's provided pre-commit hook because we need the environment management
  # supplied by `scripts/run-pyright.py`.
  - id: pyright
    name: pyright
    entry: make quick_pyright
    stages: [pre-push]
    # This means pre-commit will not try to install a new environment for this hook. It relies on
    # having a pre-existing `make` installed (and scripts/run-pyright.py).
    language: system
    pass_filenames: false
    types: [python]
