[build-system]
requires = [
    "setuptools>=69.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "dagster-snowflake"
version = "0.28.15rc1"
description = "Package for Snowflake Dagster framework components."
authors = [
    { name = "Dagster Labs", email = "hello@dagsterlabs.com" },
]
license = "Apache-2.0"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "dagster==1.12.15rc1",
    "snowflake-snowpark-python>=1.24.0",
    "snowflake-core>=1.8.0",
    "snowflake-connector-python>=3.4.0",
    "pyOpenSSL>=22.1.0",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-snowflake"

[project.entry-points."dagster_dg_cli.registry_modules"]
dagster_snowflake = "dagster_snowflake"

[project.optional-dependencies]
"snowflake.sqlalchemy" = [
    "sqlalchemy!=1.4.42",
    "snowflake-sqlalchemy",
]
pandas = [
    "pandas<3.0.0",
    "snowflake-connector-python[pandas]>=3.4.0",
]

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "dagster_snowflake_tests*",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "tox.ini",
    "pytest.ini",
    "dagster_snowflake_tests/**",
]
