[project]
name = "dagster_tutorial"
requires-python = ">=3.9,<3.15"
version = "0.1.0"
dependencies = [
    "dagster==1.11.6",
    "dagster-duckdb",
]

[dependency-groups]
dev = [
    "dagster-webserver",
    "dagster-dg-cli",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "dagster_tutorial"
registry_modules = [
    "dagster_tutorial.components.*",
]
