[build-system]
requires = ["setuptools>=69.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dagster-gcp-pyspark"
version = "1!0+dev"
description = "Package for storing PySpark DataFrames in GCP"
authors = [{name = "Dagster Labs", email = "hello@dagsterlabs.com"}]
license = "Apache-2.0"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
dependencies = [
    "dagster==1!0+dev",
    "dagster-gcp==1!0+dev",
    "pyspark>=4.1; python_version>='3.14'",
    "pyspark>=3.5,<4; python_version<'3.14'",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-gcp-pyspark"

[project.optional-dependencies]
test = [
    "pandas-gbq",
]

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "dagster_gcp_pyspark_tests*",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "tox.ini",
    "pytest.ini",
    "dagster_gcp_pyspark_tests/**",
]
