[project]
name = "project_ask_ai_dagster"
version = "0.0.1"
description = "Project RAG"
readme = "README.md"
requires-python = ">=3.9,<3.14"
dependencies = [
    "langchain",
    "langchain-core",
    "gql",
    "python-dotenv",
    "langchain-community",
    "langchain-openai",
    "langchain-chroma",
    "dagster",
    "dagster-dg-cli",
    "dagster-openai",
    "dagster_duckdb",
    "chromadb",
    "tokenizers",
    "tenacity",
    "tqdm",
    "bs4",
    "lxml",
    "openai",
    "pinecone",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest",
    "dagster-webserver",
]

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "project_ask_ai_dagster"

[tool.dg.project.python_environment]
active = true
