2.7.18:
  base_image:
    name: buildkite-integration-base
    source: aws
3.6.11:
  base_image:
    name: buildkite-integration-base
    source: aws
3.7.8:
  base_image:
    name: buildkite-integration-base
    source: aws
3.8.3:
  base_image:
    name: buildkite-integration-base
    source: aws
