[build-system]
requires = [
    "setuptools>=69.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "dagster-fivetran"
version = "0.28.15rc2"
description = "Package for integrating Fivetran with Dagster."
authors = [
    { name = "Dagster Labs", email = "hello@dagsterlabs.com" },
]
license = "Apache-2.0"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "dagster==1.12.15rc2",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-fivetran"

[project.scripts]
dagster-fivetran = "dagster_fivetran.cli:main"

[project.entry-points."dagster_dg_cli.registry_modules"]
dagster_fivetran = "dagster_fivetran"

[project.optional-dependencies]
managed = [
    "dagster-managed-elements==0.28.15rc2",
]
test = [
    "pytest-order",
]

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "dagster_fivetran_tests*",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "tox.ini",
    "pytest.ini",
    "dagster_fivetran_tests/**",
]
