version: 2

workflows:
  version: 2
  test:
    jobs:
      - lint
      - dagster-py37:
          context: coveralls
      - dagster-py36:
          context: coveralls
      - dagster-py35:
          context: coveralls
      - dagster-py27:
          context: coveralls
      - dagit-py37:
          context: coveralls
      - dagit-py36:
          context: coveralls
      - dagit-py35:
          context: coveralls
      - dagit-py27:
          context: coveralls
      - dagit-webapp:
          context: coveralls
      - dagstermill-py37:
          context: coveralls
      - dagstermill-py36:
          context: coveralls
      - dagstermill-py35:
          context: coveralls
      - dagstermill-py27:
          context: coveralls
      - airline-demo-py37:
          context: coveralls
      - airline-demo-py36:
          context: coveralls
      - airline-demo-py35:
          context: coveralls
      - airline-demo-py27:
          context: coveralls
      - dagster-contrib-py37:
          context: coveralls
      - dagster-contrib-py36:
          context: coveralls
      - dagster-contrib-py35:
          context: coveralls
      - dagster-contrib-py27:
          context: coveralls
      - dagma-py36:
          context: coveralls
      # - dagma-py35:
      #     context: coveralls
      # - dagma-py27:
      #     context: coveralls

      - coverage:
          requires:
            - dagster-py37
            - dagster-py36
            - dagster-py35
            - dagster-py27
            - dagit-py37
            - dagit-py36
            - dagit-py35
            - dagit-py27
            - dagstermill-py36
            - dagstermill-py35
            - dagstermill-py27
            - airline-demo-py36
            - airline-demo-py35
            - airline-demo-py27
            - dagster-contrib-py37
            - dagster-contrib-py36
            - dagster-contrib-py35
            - dagster-contrib-py27
            - dagma-py36
            # - dagma-py35
            # - dagma-py27
          context: coveralls



jobs:
  lint:
    docker:
      - image: circleci/python:3.7.2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install -e python_modules/dagster
            sudo pip install -r python_modules/dagster/dev-requirements.txt
            sudo pip install -e python_modules/dagit
            sudo pip install -e python_modules/dagit/dev-requirements.txt
            sudo pip install -e python_modules/dagstermill
            sudo pip install -e python_modules/dagster-contrib

      - attach_workspace:
          at: /tmp/workspace

      # only block warnings for now
      - run: pylint python_modules/dagster/dagster python_modules/dagit/dagit python_modules/dagstermill/dagstermill python_modules/dagster-contrib/dagster_contrib --rcfile=python_modules/.pylintrc --disable=R,C

  dagster-py36: &dagster-template
    docker:
      - image: circleci/python:3.6.6
    environment:
      TOXENV: py36
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install tox

      - run:
          name: Run Dagster Tests
          command: |
            cd python_modules/dagster
            tox -e $TOXENV

      - run:
          command: mv python_modules/dagster/.coverage python_modules/dagster/.coverage.dagster.${CIRCLE_BUILD_NUM}

      - persist_to_workspace:
          root: python_modules/dagster/
          paths:
            - .coverage*

  dagit-py36: &dagit-template
    <<: *dagster-template
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install tox

      - run:
          name: Run Dagit Tests
          command: |
            cd python_modules/dagit
            tox -e $TOXENV

      - run:
          command: mv python_modules/dagit/.coverage python_modules/dagit/.coverage.dagit.${CIRCLE_BUILD_NUM}

      - persist_to_workspace:
          root: python_modules/dagit/
          paths:
            - .coverage*

  dagma-py36: &dagma-template
    <<: *dagster-template
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install tox

      - run:
          name: Run Dagma Tests
          command: |
            cd python_modules/dagma
            tox -e $TOXENV

      - run:
          command: mv python_modules/dagma/.coverage python_modules/dagma/.coverage.dagma.${CIRCLE_BUILD_NUM}

      - persist_to_workspace:
          root: python_modules/dagma/
          paths:
            - .coverage*

  dagster-py37:
    <<: *dagster-template
    docker:
      - image: circleci/python:3.7.2
    environment:
      TOXENV: py37

  dagster-py35:
    <<: *dagster-template
    docker:
      - image: circleci/python:3.5.6
    environment:
      TOXENV: py35

  dagit-py37:
    <<: *dagit-template
    docker:
      - image: circleci/python:3.7.2
    environment:
      TOXENV: py37

  dagit-py35:
    <<: *dagit-template
    docker:
      - image: circleci/python:3.5.6
    environment:
      TOXENV: py35

  dagma-py35:
    <<: *dagma-template
    docker:
      - image: circleci/python:3.5.6
    environment:
      TOXENV: py35

  dagster-py27:
    <<: *dagster-template
    docker:
      - image: circleci/python:2.7.15
    environment:
      TOXENV: py27

  dagit-py27:
    <<: *dagit-template
    docker:
      - image: circleci/python:2.7.15
    environment:
      TOXENV: py27

  dagma-py27:
    <<: *dagma-template
    docker:
      - image: circleci/python:2.7.15
    environment:
      TOXENV: py27

  dagit-webapp:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            cd js_modules/dagit
            yarn

      - run:
          name: Run Typescript
          command: |
            cd js_modules/dagit
            yarn run ts

      - run:
          name: Run Tests
          command: |
            cd js_modules/dagit
            yarn run jest

      - run:
          name: Check coding style
          command: |
            cd js_modules/dagit
            yarn run check-prettier

  dagstermill-py36: &dagstermill-template
    <<: *dagster-template
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install tox

      - run:
          name: Run dagstermill Tests
          command: |
            cd python_modules/dagstermill
            tox -e $TOXENV

      - run:
          command: mv python_modules/dagstermill/.coverage python_modules/dagstermill/.coverage.dagstermill.${CIRCLE_BUILD_NUM}

      - persist_to_workspace:
          root: python_modules/dagstermill/
          paths:
            - .coverage*

  dagstermill-py37:
    <<: *dagstermill-template
    docker:
      - image: circleci/python:3.7.2
    environment:
      TOXENV: py37

  dagstermill-py35:
    <<: *dagstermill-template
    docker:
      - image: circleci/python:3.5.6
    environment:
      TOXENV: py35

  dagstermill-py27:
    <<: *dagstermill-template
    docker:
      - image: circleci/python:2.7.15
    environment:
      TOXENV: py27

  airline-demo-py36: &airline-demo-template
    <<: *dagster-template
    docker:
      - image: dagster/cci-test:3.6
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    environment:
      TOXENV: py36

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install tox

      - run:
          name: Run airline-demo Tests
          command: |
            cd python_modules/airline-demo
            tox -e $TOXENV

      - run:
          command: mv python_modules/airline-demo/.coverage python_modules/airline-demo/.coverage.airline-demo.${CIRCLE_BUILD_NUM}

      - persist_to_workspace:
          root: python_modules/airline-demo/
          paths:
            - .coverage*

  airline-demo-py37:
    <<: *airline-demo-template
    docker:
      # FIXME: https://github.com/dagster-io/dagster/issues/521 
      - image: schrockn/cci-test:3.7.2
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    environment:
      TOXENV: py37

  airline-demo-py35:
    <<: *airline-demo-template
    docker:
      - image: dagster/cci-test:3.5
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    environment:
      TOXENV: py35

  airline-demo-py27:
    <<: *airline-demo-template
    docker:
      - image: dagster/cci-test:2.7
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    environment:
      TOXENV: py27

  coverage:
    docker:
      - image: circleci/python:3.6.6
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install coverage coveralls

      - attach_workspace:
          at: /tmp/workspace

      - run: |
          cp /tmp/workspace/.coverage* .
          coverage combine
          coveralls


  dagster-contrib-py36: &dagster-contrib-template
    <<: *dagster-template
    docker:
      - image: dagster/cci-test:3.6
    environment:
      TOXENV: py36

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install tox

      - run:
          name: Run dagster-contrib Tests
          command: |
            cd python_modules/dagster-contrib
            tox -e $TOXENV

      - run:
          command: mv python_modules/dagster-contrib/.coverage python_modules/dagster-contrib/.coverage.airline-demo.${CIRCLE_BUILD_NUM}

      - persist_to_workspace:
          root: python_modules/dagster-contrib/
          paths:
            - .coverage*

  dagster-contrib-py37:
    <<: *dagster-contrib-template
    docker:
      # FIXME: https://github.com/dagster-io/dagster/issues/521 
      - image: schrockn/cci-test:3.7.2
    environment:
      TOXENV: py37

  dagster-contrib-py35:
    <<: *dagster-contrib-template
    docker:
      - image: dagster/cci-test:3.5
    environment:
      TOXENV: py35

  dagster-contrib-py27:
    <<: *dagster-contrib-template
    docker:
      - image: dagster/cci-test:2.7
    environment:
      TOXENV: py27
