version: 2

workflows:
  version: 2
  test:
    jobs:
      - dagster-python-3.6
      - dagster-python-3.5
      - dagster-python-2.7
      - dagit-webapp
      - dagit-python-3.6
      - dagit-python-3.5
      - dagit-python-2.7
      - dagstermill-python-3.6
      - dagstermill-python-3.5
      - dagstermill-python-2.7

jobs:
  dagster-python-3.6: &dagster-template
    docker:
      - image: circleci/python:3.6.6
    environment:
      TOXENV: py36
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install tox

      - run:
          name: Run Dagster Tests
          command: |
            cd python_modules/dagster
            tox -e $TOXENV

      - store_artifacts:
          path: test-reports
          destination: test-reports

  dagit-python-3.6: &dagit-template
    <<: *dagster-template
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install tox

      - run:
          name: Run Dagit Tests
          command: |
            cd python_modules/dagit
            tox -e $TOXENV

      - store_artifacts:
          path: test-reports
          destination: test-reports

  dagster-python-3.5:
    <<: *dagster-template
    docker:
      - image: circleci/python:3.5.6
    environment:
      TOXENV: py35

  dagit-python-3.5:
    <<: *dagit-template
    docker:
      - image: circleci/python:3.5.6
    environment:
      TOXENV: py35

  dagster-python-2.7:
    <<: *dagster-template
    docker:
      - image: circleci/python:2.7.15
    environment:
      TOXENV: py27

  dagit-python-2.7:
    <<: *dagit-template
    docker:
      - image: circleci/python:2.7.15
    environment:
      TOXENV: py27

  dagit-webapp:
    docker:
      - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            cd python_modules/dagit/dagit/webapp
            yarn

      - run:
          name: Run Typescript
          command: |
            cd python_modules/dagit/dagit/webapp
            yarn run ts

      - run:
          name: Run Tests
          command: |
            cd python_modules/dagit/dagit/webapp
            yarn run jest

      - run:
          name: Check coding style
          command: |
            cd python_modules/dagit/dagit/webapp
            yarn run check-prettier

      - store_artifacts:
          path: test-reports
          destination: test-reports

  dagstermill-python-3.6: &dagstermill-template
    <<: *dagster-template
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install tox

      - run:
          name: Run dagstermill Tests
          command: |
            cd python_modules/dagstermill
            tox -e $TOXENV

      - store_artifacts:
          path: test-reports
          destination: test-reports

  dagstermill-python-3.5:
    <<: *dagstermill-template
    docker:
      - image: circleci/python:3.5.6
    environment:
      TOXENV: py35

  dagstermill-python-2.7:
    <<: *dagstermill-template
    docker:
      - image: circleci/python:2.7.15
    environment:
      TOXENV: py27
