{{- if .Values.rbacEnabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "dagster.fullname" . }}-role
  labels: {{ include "dagster.labels" . | nindent 4 }}

# Allow the Dagster service account to read and write Kubernetes jobs, deployments, pods, and events.
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs/status"]
    verbs: ["get", "watch", "list"]
  # The empty arg "" corresponds to the core API group
  - apiGroups: [""]
    resources: ["pods", "events"]
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods/log", "pods/status"]
    verbs: ["get", "watch", "list"]
{{- end -}}
