[build-system]
requires = [
    "setuptools>=69.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "dagster-sling"
version = "0.28.15rc1"
description = "Package for performing ETL/ELT tasks with Sling in Dagster."
authors = [
    { name = "Dagster Labs", email = "hello@dagsterlabs.com" },
]
license = "Apache-2.0"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "dagster==1.12.15rc1",
    "sling>=1.1.5",
    "sling-mac-arm64; platform_system=='Darwin' and platform_machine=='arm64'",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-sling"

[project.entry-points."dagster_dg_cli.registry_modules"]
dagster_sling = "dagster_sling"

[project.optional-dependencies]
test = [
    "duckdb",
    "dagster-dg-cli",
]

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "dagster_sling_tests*",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "tox.ini",
    "pytest.ini",
    "dagster_sling_tests/**",
]
