[build-system]
requires = [
    "setuptools>=69.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "dagster-dask"
version = "0.28.15rc4"
description = "Package for using Dask as Dagster's execution engine."
authors = [
    { name = "Dagster Labs", email = "hello@dagsterlabs.com" },
]
license = "Apache-2.0"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "bokeh",
    "dagster==1.12.15rc4",
    "dask[dataframe]>=1.2.2",
    "distributed>=1.28.1",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-dask"

[project.optional-dependencies]
yarn = [
    "dask-yarn",
]
pbs = [
    "dask-jobqueue",
]
kube = [
    "dask-kubernetes<=2022.9.0",
]
test = [
    "pyarrow",
]

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "dagster_dask_tests*",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "tox.ini",
    "pytest.ini",
    "dagster_dask_tests/**",
]
