blank_issues_enabled: false
contact_links:
  - name: ğŸŒŸ Star us on Github
    url: https://github.com/dagster-io/dagster
    about: Show your support by starring the project!
  - name: ğŸ¦ Follow us on Twitter
    url: https://twitter.com/dagsterio
    about: Get notifications about Dagster content from our Twitter account.
  - name: ğŸ“º Subscribe to our YouTube channel
    url: https://www.youtube.com/channel/UCfLnv9X8jyHTe6gJ4hVBo9Q
    about: Watch videos about Dagster content from our YouTube account.
  - name: ğŸ“š Read our blog posts
    url: https://dagster.io/blog
    about: Read about the latest updates in Dagster.
  - name: ğŸ‘‹ Join us on Slack
    url: https://dagster.io/slack
    about: Connect with thousands of other data practitioners building with Dagster. Share knowledge, get help, and contribute to the open-source project.
  - name: âœï¸ Start a Github Discussion
    url: https://github.com/dagster-io/dagster/discussions
    about: Interact with the community and Dagster core team over Github Discussions.
