version: "3.7"

# These are the services and networks that are referenced when running MySQL tests.  They should be
# referenced in both the standard conftest.py as well as the MySQL section in the buildkite
# steps/packages.py file
services:
  # This is the standard MySQL test instance, running the latest version of MySQL. We use this for
  # all of our storage tests.
  test-mysql-db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: test-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_USER: "test"
      MYSQL_DATABASE: "test"
    networks:
      - mysql

  # This is our pinned MySQL test instance, running a pinned, older version of MySQL. We also use
  # this for all of our storage tests, to ensure that we're using a reasonable set of supported SQL
  # syntax (e.g. excluding INTERSECT_ALL). We also run this instance using the flag
  # --sql-require-primary-key=ON, which requires all tables to have a primary key. This should stop
  # any new tables from being added that do not have a primary key.
  test-mysql-db-pinned:
    image: mysql:8.0.21
    command: mysqld --default-authentication-plugin=mysql_native_password --sql-require-primary-key=ON
    container_name: test-mysql-db-pinned
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_USER: "test"
      MYSQL_DATABASE: "test"
      MYSQL_TCP_PORT: 3307
    expose:
      - 3307
    networks:
      - mysql_pinned

  # This is the same as test-mysql-db-pinned, but we use this instance to run back-compat tests on
  # the pinned older SQL instances.  Prior to 1.2.0, we did not require primary keys on all tables,
  # so some of our back-compat tests include snapshots of DBs that would cause errors when loaded on
  # a MySQL instance with --sql-require-primary-key=ON.
  test-mysql-db-pinned-backcompat:
    image: mysql:8.0.21
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: test-mysql-db-pinned-backcompat
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_USER: "test"
      MYSQL_DATABASE: "test"
      MYSQL_TCP_PORT: 3308
    expose:
      - 3308
    networks:
      - mysql_pinned_backcompat

networks:
  mysql:
    driver: bridge
    name: mysql
  mysql_pinned:
    driver: bridge
    name: mysql_pinned
  mysql_pinned_backcompat:
    driver: bridge
    name: mysql_pinned_backcompat
