3.6.15:
  docker_args:
    BASE_IMAGE: python:3.6.15-slim
3.7.13:
  docker_args:
    BASE_IMAGE: python:3.7.13-slim
3.8.13:
  docker_args:
    BASE_IMAGE: python:3.8.13-slim
3.9.13:
  docker_args:
    BASE_IMAGE: python:3.9.13-slim
3.10.5:
  docker_args:
    BASE_IMAGE: python:3.10.5-slim
