[build-system]
requires = ["setuptools>=69.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dagster-sphinx"
version = "0.0.1"
description = "Dagster-specific sphinx extension."
authors = [{name = "Elementl", email = "hello@elementl.com"}]
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
dependencies = [
    "sphinx",
    "sphinx_toolbox",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster"

[tool.setuptools.packages.find]
exclude = [
    "dagster_sphinx_tests*",
]
