[build-system]
requires = ["setuptools>=69.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dagster-azure"
version = "1!0+dev"
description = "Package for Azure-specific Dagster framework op and resource components."
authors = [{name = "Dagster Labs", email = "hello@dagsterlabs.com"}]
license = "Apache-2.0"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "azure-core<2.0.0,>=1.7.0",
    "azure-identity<2.0.0,>=1.7.0",
    "azure-ai-ml<2.0.0,>=1.28.0",
    "azure-storage-blob<13.0.0,>=12.5.0",
    "azure-storage-file-datalake<13.0.0,>=12.5",
    "dagster==1!0+dev",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-azure"

[project.scripts]
dagster-azure = "dagster_azure.cli.cli:main"

[project.entry-points."dagster_dg_cli.registry_modules"]
dagster_azure = "dagster_azure.components"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "dagster_azure_tests*",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "tox.ini",
    "pytest.ini",
    "dagster_azure_tests/**",
]
