replicaCount: 1

imagePullPolicy: Always

nameOverride: ""
fullnameOverride: ""

rbacEnabled: true

# The DAGSTER_HOME env var is set by default on all nodes from this value
dagster_home: "/opt/dagster/dagster_home"

dagit:
  # Dagit image repository and tag to deploy
  image:
    repository: "dagster.io/dagster-docker-buildkite"
    tag: "py37-latest"

  service:
    type: ClusterIP
    port: 80

  # Can be set to override the default dagster home on the dagit containers
  dagster_home: ""
  # Additional environment variables to set on the dagit container.
  # A Kubernetes ConfigMap will be created with these environment variables.
  env:
    YOUR_ENV_VAR: ""
  # Additional environment variables can be retrieved and set from the ConfigMaps enumerated as a
  # list here
  env_config_maps:
    - ""
  # Additional (secret) environment variables can be retrieved and set from the Secrets enumerated
  # as a list here
  env_secrets:
    - ""

# Configuration for the celery/job containers, which together handle physical execution
job_runner:
  # The Dagster K8sRunLauncher will invoke job executions in containers running this image
  image:
    repository: "dagster.io/dagster-docker-buildkite"
    tag: "py37-latest"

  # Can be set to override the default dagster home on the celery/job containers
  dagster_home: ""
  # Additional environment variables to set on the celery/job containers
  # A Kubernetes ConfigMap will be created with these environment variables.
  env:
    YOUR_ENV_VAR: ""
  # Additional environment variables can be retrieved and set from the ConfigMaps enumerated as a
  # list here
  env_config_maps:
    - ""
  # Additional (secret) environment variables can be retrieved and set from the Secrets enumerated
  # as a list here
  env_secrets:
    - ""

workers:
  nameOverride: ""

# Configuration values for postgresql
# https://github.com/kubernetes/charts/blob/master/stable/postgresql/README.md
postgresql:
  # set postgresql.enabled to be false to disable deploy of a Postgres database (e.g., to use
  # RDS instead, etc.)
  enabled: true
  postgresqlUsername: test
  # Note when changing this password (e.g. in test) that credentials will
  # persist as long as the PVCs do -- see:
  # https://github.com/helm/charts/issues/12836#issuecomment-524552358
  postgresqlPassword: test
  postgresqlDatabase: test
  service:
    port: 5432

# Configuration values for celery
celery:
  # set celery.enabled to be false to disable deploy of the celery workers & rabbitmq
  enabled: true
  replicaCount: 5

# This is gated by celery.enabled above
# https://github.com/helm/charts/issues/17250#issuecomment-533444837
rabbitmq:
  rabbitmq:
    username: test
    password: test
  service:
    port: 5672
  volumePermissions:
    enabled: true

# The flower web interface
flower:
  enabled: true
  service:
    annotations:


serviceAccount:
  create: true

podSecurityContext: {}

securityContext: {}

resources:
  {}
  # If you want to specify resources, uncomment the following lines, adjust them as necessary,
  # and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
