[build-system]
requires = [
    "setuptools>=69.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "dagster-pandera"
version = "0.28.15rc0"
description = "Integration layer for dagster and pandera."
authors = [
    { name = "Dagster Labs", email = "hello@dagsterlabs.com" },
]
license = "Apache-2.0"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "dagster==1.12.15rc0",
    "pandas<3.0.0",
    "pandera>=0.24.0",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster"

[project.optional-dependencies]
polars = [
    "polars>=1",
]
test = [
    "polars>=1",
    "pytest",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
exclude = [
    "dagster_pandera_tests*",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "tox.ini",
    "dagster_pandera_tests/**",
]
