[build-system]
requires = [
    "setuptools>=69.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "dagster-celery"
version = "0.28.15rc0"
description = "Package for using Celery as Dagster's execution engine."
authors = [
    { name = "Dagster Labs", email = "hello@dagsterlabs.com" },
]
license = "Apache-2.0"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
dependencies = [
    "dagster==1.12.15rc0",
    "celery>=4.3.0",
    "click>=5.0,<9.0",
    "importlib_metadata<5.0.0; python_version<'3.8'",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-celery"

[project.scripts]
dagster-celery = "dagster_celery.cli:main"

[project.optional-dependencies]
flower = [
    "flower",
]
redis = [
    "redis",
]
kubernetes = [
    "kubernetes",
]
test = [
    "docker",
]

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "dagster_celery_tests*",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "tox.ini",
    "pytest.ini",
    "dagster_celery_tests/**",
    "conftest.py",
    "docker-compose.yaml",
]
