[build-system]
requires = [
    "setuptools>=69.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "dagit"
version = "1.12.15rc4"
description = "Web UI for dagster."
authors = [
    { name = "Dagster Labs", email = "hello@dagsterlabs.com" },
]
license = "Apache-2.0"
readme = "README.rst"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "dagster-webserver==1.12.15rc4",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster"

[project.scripts]
dagit = "dagster_webserver.cli:main"
dagit-debug = "dagster_webserver.debug:main"

[project.optional-dependencies]
notebook = [
    "dagster-webserver[notebook]==1.12.15rc4",
]
test = [
    "dagster-webserver[test]==1.12.15rc4",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
exclude = [
    "dagit_tests*",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "tox.ini",
    "dagit_tests/**",
    "build_js.sh",
]
