[project]
name = "hello_world"
requires-python = ">=3.9,<3.13"
version = "0.1.0"
dependencies = [
    "dagster",
    "dagster-graphql",
    "dagster-pipes",
    "dagster-webserver",
]

[project.optional-dependencies]
dev = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "hello_world.definitions"
project_name = "hello_world"

[tool.setuptools.packages.find]
exclude=["hello_world_tests"]

[tool.uv.sources]
dagster = { path = "../../../../../../../python_modules/dagster", editable = true }
dagster-graphql = { path = "../../../../../../../python_modules/dagster-graphql", editable = true }
dagster-webserver = { path = "../../../../../../../python_modules/dagster-webserver", editable = true }
dagster-pipes = { path = "../../../../../../../python_modules/dagster-pipes", editable = true }


