---
apiVersion: v2
name: dagster
version: 0.0.1-dev
kubeVersion: ">= 1.15.0-0"
description: Dagster is a data orchestrator for machine learning, analytics, and ETL.
type: application
keywords:
  - analytics
  - data-orchestrator
  - data-pipelines
  - etl
  - workflow
sources:
  - https://github.com/dagster-io/dagster/tree/master/helm/dagster
dependencies:
  - name: dagster-user-deployments
    version: 0.0.1-dev
    condition: dagster-user-deployments.enableSubchart
  - name: postgresql
    version: 8.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: rabbitmq
    version: 6.16.3
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: redis
    version: 12.7.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.internal
maintainers:
  - name: Rex Ledesma
    email: rex@elementl.com
    url: https://dagster.io
icon: https://dagster.io/images/logo.png
appVersion: dev
