[project]
name = "snowflake-medallion"
requires-python = ">=3.10,<3.14"
version = "0.1.0"
dependencies = [
    "dagster>=1.9.0",
    "dagster-dbt>=0.28.0",
    "pandas>=2.0.0",
    "duckdb>=0.9.0",
    "dbt-duckdb>=1.7.0",
    "snowflake-connector-python>=3.6.0",
]

[dependency-groups]
dev = ["dagster-webserver", "dagster-dg-cli", "pytest"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/snowflake_medallion"]

[tool.hatch.build.targets.wheel.sources]
"src" = ""

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "snowflake_medallion"

[tool.ruff]
lint.extend-select = ["I"]
