[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "project_dagster_modal_pipes.definitions"
code_location_name = "project_dagster_modal_pipes"

[project]
name = "project_dagster_modal_pipes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "dagster",
    "dagster-dg-cli",
    "dagster-aws",
    "dagster-modal>=0.0.2",
    "dagster-openai",
    "feedparser",
    "ffmpeg-python",
    "modal",
    "openai",
    "tiktoken",
    "yagmail",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "dagster-webserver",
]

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "project_dagster_modal_pipes"
autoload_defs = true

[tool.dg.project.python_environment]
active = true