[project]
name = "project_prompt_eng"
version = "0.0.1"
description = "Project Prompt Engineering"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dagster",
    "dagster-dg-cli",
    "dagster-anthropic",
    "pydantic",
    "requests",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest",
    "dagster-webserver",
]

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "project_prompt_eng"

[tool.dg.project.python_environment]
active = true
