[project]
name = "project_components_pdf_extraction"
requires-python = ">=3.9,<3.15"
version = "0.1.0"
dependencies = [
    "dagster-dg-cli",
    "dagster-dg-core",
    "dagster-shared",
    "dagster-openai",
    "dagster-webserver",
    "opencv-python>=4.11.0.86",
    "pdf2image>=1.17.0",
    "pytesseract>=0.3.13",
    "tool>=0.8.0",
]

[project.entry-points]
"dagster_dg_cli.registry_modules" = { project_components_pdf_extraction = "project_components_pdf_extraction.lib"}

[dependency-groups]
dev = [
    "dagster-webserver",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "project_components_pdf_extraction"
defs_module = "project_components_pdf_extraction.defs"

[tool.setuptools.packages.find]
exclude=["project_components_pdf_extraction_tests"]


[tool.uv.sources]
dagster-test = { path = '../../../python_modules/dagster-test', editable = true }
dagster-graphql = { path = '../../../python_modules/dagster-graphql', editable = true }
dagster = { path = '../../../python_modules/dagster', editable = true }
dagster-pipes = { path = '../../../python_modules/dagster-pipes', editable = true }
dagster-webserver = { path = '../../../python_modules/dagster-webserver', editable = true }
dagster-airbyte = { path = '../../../python_modules/libraries/dagster-airbyte', editable = true }
dagster-dask = { path = '../../../python_modules/libraries/dagster-dask', editable = true }
dagster-github = { path = '../../../python_modules/libraries/dagster-github', editable = true }
dagster-snowflake = { path = '../../../python_modules/libraries/dagster-snowflake', editable = true }
dagster-pagerduty = { path = '../../../python_modules/libraries/dagster-pagerduty', editable = true }
dagster-cloud-cli = { path = '../../../python_modules/libraries/dagster-cloud-cli', editable = true }
dagster-prometheus = { path = '../../../python_modules/libraries/dagster-prometheus', editable = true }
dagster-deltalake = { path = '../../../python_modules/libraries/dagster-deltalake', editable = true }
dagster-dlt = { path = '../../../python_modules/libraries/dagster-dlt', editable = true }
dagster-azure = { path = '../../../python_modules/libraries/dagster-azure', editable = true }
dagster-postgres = { path = '../../../python_modules/libraries/dagster-postgres', editable = true }
dagster-duckdb = { path = '../../../python_modules/libraries/dagster-duckdb', editable = true }
dagster-gcp-pandas = { path = '../../../python_modules/libraries/dagster-gcp-pandas', editable = true }
dagster-k8s = { path = '../../../python_modules/libraries/dagster-k8s', editable = true }
dagster-papertrail = { path = '../../../python_modules/libraries/dagster-papertrail', editable = true }
dagster-gcp-pyspark = { path = '../../../python_modules/libraries/dagster-gcp-pyspark', editable = true }
dagster-celery = { path = '../../../python_modules/libraries/dagster-celery', editable = true }
dagster-airflow = { path = '../../../python_modules/libraries/dagster-airflow', editable = true }
dagster-dbt = { path = '../../../python_modules/libraries/dagster-dbt', editable = true }
dagster-census = { path = '../../../python_modules/libraries/dagster-census', editable = true }
dagster-airlift = { path = '../../../python_modules/libraries/dagster-airlift', editable = true }
dagster-managed-elements = { path = '../../../python_modules/libraries/dagster-managed-elements', editable = true }
dagster-snowflake-pandas = { path = '../../../python_modules/libraries/dagster-snowflake-pandas', editable = true }
dagster-embedded-elt = { path = '../../../python_modules/libraries/dagster-embedded-elt', editable = true }
dagster-powerbi = { path = '../../../python_modules/libraries/dagster-powerbi', editable = true }
dagster-pandera = { path = '../../../python_modules/libraries/dagster-pandera', editable = true }
dagster-datadog = { path = '../../../python_modules/libraries/dagster-datadog', editable = true }
dagster-celery-k8s = { path = '../../../python_modules/libraries/dagster-celery-k8s', editable = true }
dagster-pandas = { path = '../../../python_modules/libraries/dagster-pandas', editable = true }
dagster-openai = { path = '../../../python_modules/libraries/dagster-openai', editable = true }
dagster-twilio = { path = '../../../python_modules/libraries/dagster-twilio', editable = true }
dagster-gcp = { path = '../../../python_modules/libraries/dagster-gcp', editable = true }
dagstermill = { path = '../../../python_modules/libraries/dagstermill', editable = true }
dagster-duckdb-pandas = { path = '../../../python_modules/libraries/dagster-duckdb-pandas', editable = true }
dagster-ge = { path = '../../../python_modules/libraries/dagster-ge', editable = true }
dagster-sigma = { path = '../../../python_modules/libraries/dagster-sigma', editable = true }
dagster-pyspark = { path = '../../../python_modules/libraries/dagster-pyspark', editable = true }
dagster-ssh = { path = '../../../python_modules/libraries/dagster-ssh', editable = true }
dagster-deltalake-polars = { path = '../../../python_modules/libraries/dagster-deltalake-polars', editable = true }
dagster-mysql = { path = '../../../python_modules/libraries/dagster-mysql', editable = true }
dagster-docker = { path = '../../../python_modules/libraries/dagster-docker', editable = true }
dagster-duckdb-pyspark = { path = '../../../python_modules/libraries/dagster-duckdb-pyspark', editable = true }
dagster-looker = { path = '../../../python_modules/libraries/dagster-looker', editable = true }
dagster-duckdb-polars = { path = '../../../python_modules/libraries/dagster-duckdb-polars', editable = true }
dagster-msteams = { path = '../../../python_modules/libraries/dagster-msteams', editable = true }
dagster-datahub = { path = '../../../python_modules/libraries/dagster-datahub', editable = true }
dagster-databricks = { path = '../../../python_modules/libraries/dagster-databricks', editable = true }
dagster-deltalake-pandas = { path = '../../../python_modules/libraries/dagster-deltalake-pandas', editable = true }
dagster-fivetran = { path = '../../../python_modules/libraries/dagster-fivetran', editable = true }
dagster-sling = { path = '../../../python_modules/libraries/dagster-sling', editable = true }
dagster-dg-cli = { path = '../../../python_modules/libraries/dagster-dg-cli', editable = true }
dagster-slack = { path = '../../../python_modules/libraries/dagster-slack', editable = true }
dagster-aws = { path = '../../../python_modules/libraries/dagster-aws', editable = true }
dagster-dg-core = { path = '../../../python_modules/libraries/dagster-dg-core', editable = true }
dagster-mlflow = { path = '../../../python_modules/libraries/dagster-mlflow', editable = true }
dagster-tableau = { path = '../../../python_modules/libraries/dagster-tableau', editable = true }
dagster-shared = { path = '../../../python_modules/libraries/dagster-shared', editable = true }
dagster-snowflake-pyspark = { path = '../../../python_modules/libraries/dagster-snowflake-pyspark', editable = true }
dagster-celery-docker = { path = '../../../python_modules/libraries/dagster-celery-docker', editable = true }
dagster-spark = { path = '../../../python_modules/libraries/dagster-spark', editable = true }
dagster-wandb = { path = '../../../python_modules/libraries/dagster-wandb', editable = true }
