[build-system]
requires = [
    "setuptools>=69.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "dagster-aws"
version = "0.28.15rc1"
description = "Package for AWS-specific Dagster framework solid and resource components."
authors = [
    { name = "Dagster Labs", email = "hello@dagsterlabs.com" },
]
license = "Apache-2.0"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "boto3",
    "dagster==1.12.15rc1",
    "packaging",
    "requests",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-aws"

[project.entry-points."dagster_dg_cli.registry_modules"]
dagster_aws = "dagster_aws.components"

[project.optional-dependencies]
redshift = [
    "psycopg2-binary",
]
pyspark = [
    "dagster-pyspark==0.28.15rc1",
]
stubs = [
    "boto3-stubs-lite[s3,logs,ecs,glue,emr-serverless,emr,emr-containers]",
]
test = [
    "botocore!=1.32.1",
    "moto[s3,server,glue,emrserverless,logs,emrcontainers]>=2.2.8,<5.0",
    "requests-mock",
    "xmltodict==0.12.0",
    "flaky",
    "pytest-cases",
    "s3fs",
]

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "dagster_aws_tests*",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "tox.ini",
    "pytest.ini",
    "dagster_aws_tests/**",
]
