{{- if .Values.flower.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dagster.flower.fullname" . }}
  labels:
    {{- include "dagster.labels" . | nindent 4 }}
    component: flower
  annotations:
    {{- range $key, $value := .Values.flower.annotations }}
    {{ $key }}: {{ $value | squote }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dagster.selectorLabels" . | nindent 6 }}
      component: flower
  template:
    metadata:
      labels:
        {{- include "dagster.selectorLabels" . | nindent 8 }}
        component: flower
      annotations:
        checksum/dagster-instance: {{ include (print $.Template.BasePath "/configmap-instance.yaml") . | sha256sum }}
        {{- range $key, $value := .Values.flower.annotations }}
        {{ $key }}: {{ $value | squote }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dagster.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.flower.podSecurityContext | nindent 8 }}
      initContainers:
        - name: check-db-ready
          image: "{{- $.Values.postgresql.image.repository -}}:{{- $.Values.postgresql.image.tag -}}"
          imagePullPolicy: "{{- $.Values.postgresql.image.pullPolicy -}}"
          command: ['sh', '-c',
            'until pg_isready -h {{ include "dagster.postgresql.host" . }} -p {{ .Values.postgresql.service.port }}; do echo waiting for database; sleep 2; done;',
            ]
          securityContext:
            {{- toYaml .Values.flower.securityContext | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.flower.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.flower.image.pullPolicy }}
          image: {{ include "image.name" .Values.flower.image | quote }}
          args: ["flower"]
          envFrom:
            - configMapRef:
                name: {{ template "dagster.fullname" . }}-flower-env
          env:
            - name: CELERY_BROKER_URL
              value: "{{ include "dagster.celery.broker_url" . }}"
            - name: CELERY_RESULT_BACKEND
              value: "{{ include "dagster.celery.backend_url" . }}"
          volumeMounts: []
          ports:
            - name: flower
              containerPort: 5555
              protocol: TCP
          resources:
      {{- toYaml .Values.flower.resources | nindent 12 }}
      {{- with .Values.flower.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes: []
      {{- with .Values.flower.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}