{{- $_ := include "dagster.backcompat" . | mustFromJson -}}
{{- $apiVersion := .Values.ingress.apiVersion | default "" }}
{{- $hasApiVersion := (.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress") }}
{{- $hasOverrideApiVersion := eq $apiVersion "networking.k8s.io/v1/Ingress" }}
{{- $hasOverrideBetaApiVersion := eq $apiVersion "extensions/v1beta1/Ingress" }}
{{- if and (.Values.ingress.enabled) (not $hasOverrideBetaApiVersion) (or $hasApiVersion $hasOverrideApiVersion) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dagster.fullname" . }}-ingress
  labels:
    {{- include "dagster.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.ingress.labels }}
    {{ $key }}: {{ $value | squote }}
    {{- end }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | squote }}
    {{- end }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    {{- if $_.Values.ingress.dagsterWebserver.tls.enabled }}
    - hosts:
        - {{ $_.Values.ingress.dagsterWebserver.host }}
      secretName: {{ $_.Values.ingress.dagsterWebserver.tls.secretName }}
    {{- end }}
    {{- if $_.Values.ingress.readOnlyDagsterWebserver.tls.enabled }}
    - hosts:
        - {{ $_.Values.ingress.readOnlyDagsterWebserver.host }}
      secretName: {{ $_.Values.ingress.readOnlyDagsterWebserver.tls.secretName }}
    {{- end }}
    {{- if .Values.ingress.flower.tls.enabled }}
    - hosts:
        - {{ .Values.ingress.flower.host }}
      secretName: {{ .Values.ingress.flower.tls.secretName }}
    {{- end }}
  rules:
    - host: {{ $_.Values.ingress.dagsterWebserver.host }}
      http:
        paths:
          {{- range $_.Values.ingress.dagsterWebserver.precedingPaths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port: {{- include "ingress.service.port" . | nindent 16 }}
          {{- end }}
          - path: {{ $_.Values.ingress.dagsterWebserver.path | default "/*" }}
            pathType: {{ $_.Values.ingress.dagsterWebserver.pathType }}
            backend:
              service:
                name: {{ include "dagster.webserver.fullname" . }}
                port:
                  number: {{ $_.Values.dagsterWebserver.service.port | default 80 }}
          {{- range $_.Values.ingress.dagsterWebserver.succeedingPaths }}
          - path: {{ .path }}
            backend:
              service:
                name: {{ .serviceName }}
                port: {{- include "ingress.service.port" . | nindent 16 }}
          {{- end }}
    {{- if $_.Values.dagsterWebserver.enableReadOnly }}
    - host: {{ $_.Values.ingress.readOnlyDagsterWebserver.host }}
      http:
        paths:
          {{- range $_.Values.ingress.readOnlyDagsterWebserver.precedingPaths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port: {{- include "ingress.service.port" . | nindent 16 }}
          {{- end }}
          - path: {{ $_.Values.ingress.readOnlyDagsterWebserver.path | default "/*" }}
            pathType: {{ $_.Values.ingress.readOnlyDagsterWebserver.pathType }}
            backend:
              service:
                name: {{ template "dagster.webserver.fullname" dict "Values" .Values "Release" .Release "webserverReadOnly" true }}
                port:
                  number: {{ $_.Values.dagsterWebserver.service.port | default 80 }}
          {{- range $_.Values.ingress.readOnlyDagsterWebserver.succeedingPaths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port: {{- include "ingress.service.port" . | nindent 16 }}
          {{- end }}
    {{end}}
    {{- if .Values.flower.enabled }}
    - host: {{ .Values.ingress.flower.host }}
      http:
        paths:
          {{- range .Values.ingress.flower.precedingPaths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port: {{- include "ingress.service.port" . | nindent 16 }}
          {{- end }}
          - path: {{ .Values.ingress.flower.path | default "/*" }}
            pathType: {{ .Values.ingress.flower.pathType }}
            backend:
              service:
                name: {{ template "dagster.fullname" . }}-flower-service
                port:
                  number: {{ .Values.flower.service.port }}
          {{- range .Values.ingress.flower.succeedingPaths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port: {{- include "ingress.service.port" . | nindent 16 }}
          {{- end }}
    {{end}}
{{end}}
