[build-system]
requires = [
    "setuptools>=69.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "dagster-webserver"
version = "1.12.15rc3"
description = "Web UI for dagster."
authors = [
    { name = "Dagster Labs", email = "hello@dagsterlabs.com" },
]
license = "Apache-2.0"
readme = "README.rst"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "click>=7.0,<9.0",
    "dagster==1.12.15rc3",
    "dagster-graphql==1.12.15rc3",
    "starlette!=0.36.0",
    "uvicorn[standard]",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster"

[project.scripts]
dagster-webserver = "dagster_webserver.cli:main"
dagster-webserver-debug = "dagster_webserver.debug:main"

[project.optional-dependencies]
notebook = [
    "nbconvert",
]
test = [
    "starlette[full]",
]

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "dagster_webserver_tests*",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "tox.ini",
    "dagster_webserver_tests/**",
    "build_js.sh",
]
