[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "dagster_pypi.definitions"
code_location_name = "dagster_pypi"

[tool.ruff]

src = ["dagster_pypi"]

# Extend root configuration.
extend = "../../pyproject.toml"

[tool.ruff.lint]
# Use extend-ignore so that we ignore all the same codes ignored in root.
extend-ignore = [
  # (print found): Allow prints for demo purposes.
  "T201",

  # (relative imports): relative imports are acceptable in examples & docs
  "TID252"

]
