[project]
name = "multi-platform-data-local"
requires-python = ">=3.10,<3.14"
version = "0.1.0"
dependencies = [
    "dagster>=1.9.0",
    "dagster-webserver>=1.9.0",
    "dagster-dg-cli>=1.0.0",
]

[tool.hatch.build.targets.wheel]
only-include = []
