[build-system]
requires = [
    "setuptools>=69.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "dagster_sigma"
version = "0.28.15rc4"
description = "Build assets representing Sigma dashboards."
authors = [
    { name = "Dagster Labs", email = "hello@dagsterlabs.com" },
]
license = "Apache-2.0"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "dagster==1.12.15rc4",
    "sqlglot",
    "aiohttp",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-sigma"

[project.scripts]
dagster-sigma = "dagster_sigma.cli:app"

[project.optional-dependencies]
test = [
    "aioresponses",
    "aiohttp<3.11",
]

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "dagster_sigma_tests*",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "tox.ini",
    "pytest.ini",
    "dagster_sigma_tests/**",
]
