---
apiVersion: v2
name: dagster-user-deployments
version: 0.0.1-dev
kubeVersion: ">= 1.18.0-0"
description: A chart to deploy code servers for your Dagster deployment.
type: application
keywords:
  - analytics
  - data-orchestrator
  - data-pipelines
  - etl
  - workflow
sources:
  - https://github.com/dagster-io/dagster/tree/master/helm/dagster/charts/dagster-user-deployments
maintainers:
  - name: Dagster Labs
    email: support@dagsterlabs.com
    url: https://dagster.io/about
icon: https://dagster.io/images/brand/logos/dagster-primary-mark.png
appVersion: dev
