---
apiVersion: v2
name: dagster-user-deployments
version: 0.0.1-dev
kubeVersion: ">= 1.15.0-0"
description: A chart to deploy Dagster User Code deployments.
type: application
keywords:
  - analytics
  - data-orchestrator
  - data-pipelines
  - etl
  - workflow
sources:
  - https://github.com/dagster-io/dagster/tree/master/helm/dagster/charts/dagster-user-deployments
maintainers:
  - name: Rex Ledesma
    email: rex@elementl.com
    url: https://dagster.io
icon: https://dagster.io/images/logo.png
appVersion: dev
