[build-system]
requires = [
    "setuptools>=69.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "dagster-graphql"
version = "1.12.15rc3"
description = "The GraphQL API for Dagster."
authors = [
    { name = "Dagster Labs", email = "hello@dagsterlabs.com" },
]
license = "Apache-2.0"
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "dagster==1.12.15rc3",
    "graphene>=3,<4",
    "gql[requests]>=3,<5",
    "requests",
    "starlette",
]

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-graphql"

[project.scripts]
dagster-graphql = "dagster_graphql.cli:main"

[project.optional-dependencies]
test = [
    "dagster-test",
]

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "dagster_graphql_tests*",
]

[tool.check-manifest]
ignore = [
    ".coveragerc",
    "pytest.ini",
    "tox.ini",
    "tox_postgres.ini",
    "dagster_graphql_tests/**",
]
